version: '3'

services:
  db:
      image: postgres
      container_name: "postgres"
      environment:
        - POSTGRES_USER=''
        - POSTGRES_PASSWORD=''
        - POSTGRES_DB=''
      ports:
            - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    container_name: 'django'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: .
    container_name: 'celery'
    command: celery -A dormitory worker --loglevel=info -E
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  flower:
    image: mher/flower
    container_name: 'celery_flower'
    command: ["flower", "--broker=redis://redis:6379", "--port=8888"]
    ports:
      - 8888:8888
    depends_on:
      - celery